version: "3.8"

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentry-zoho-integration_app
    ports:
      - "${HOST_PORT}:80"
    environment:
      - ZOHO_CLIQ_WEBHOOK_URL=${ZOHO_CLIQ_WEBHOOK_URL}
      - ZOHO_CLIQ_DEFAULT_CHANNEL=${ZOHO_CLIQ_DEFAULT_CHANNEL}
      - ZOHO_CLIQ_CHANNELS=${ZOHO_CLIQ_CHANNELS}
    restart: always
    privileged: true
